name: soloup
description: A habit tracker with XP system, anime theme, and procrastination lock.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.1.0
  percent_indicator: ^4.2.3
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/characters/
    - assets/sounds/
